### ISSUE TITLE
Nepali Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ne.reactjs.org#1]
## Maintainer List

* @samundrak
* @nootanghimire
* @pachabhaiya 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@samundrak) #4 
* [x] Tutorial (@madhusudhan1234) #6 

### Basics

* [ ] Hello World (@samundrak) #7 
* [ ] Introducing JSX
* [ ] Rendering Elements
* [ ] Components and Props
* [x] State and Lifecycle (@Acesmndr) #21
* [ ] Handling Events (@madhusudhan1234)
* [ ] Conditional Rendering
* [ ] Lists and Keys
* [ ] Forms
* [ ] Lifting State Up
* [ ] Composition vs Inheritance
* [ ] Thinking in React

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@madhusudhan1234) #6
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started
* [ ] Add React to a Website
* [ ] Create a New React App
* [x] CDN Links (@pachabhaiya) #11 

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] Introducing Hooks
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by samundrak** [comment]
hi @tesseralis , was there any reason to change the language code from `np` to `ne` ?

**Comment by tesseralis** [comment]
ne is the ISO 639-1 code for Nepali and the one we’re using. (For example, Nepali Wikipedia is ne.wikipedia.org). We’re using language codes instead of country codes because it’s more neutral. For example, for Japanese we’re using “ja” (language code) instead of “jp” (country code)

**Comment by samundrak** [comment]
Sorry! was confused about country and language code :smile:

**Comment by duwalanise** [comment]
Hey team, I would like to translate Hello world page.

**Comment by samundrak** [comment]
hi @duwalanise, thanks for your interest. can you please pick another page as `hello world` page is currently being translated and also do open PR once you start translating

**Comment by tesseralis** [comment]
@samundrak could you update the issue since there's a PR out?

**Comment by duwalanise** [comment]
Sure @samundrak, I will start with Introducing JSX then.

**Comment by madhusudhan1234** [comment]
Hi @samundrak, ```tutorial/nav.yml``` is translated along with [this PR](https://github.com/reactjs/ne.reactjs.org/pull/6), Please check.

**Comment by samundrak** [comment]
thanks @madhusudhan1234

**Comment by barshalamixaane** [comment]
Hi Guys! I am just starting to translate components and props. Thanks!

**Comment by Acesmndr** [comment]
I'm translating state and lifecycle page.

**Comment by nootanghimire** [comment]
@barshalamixaane Apologies for late reply, I just had a chance to look at your PR. I've left some comments there! 

@Acesmndr sweet! Looking forward to it!

**Comment by Acesmndr** [comment]
@nootanghimire Just completed the translation for State and Lifecycle page in https://github.com/reactjs/ne.reactjs.org/pull/21 .  समीक्षाको आवश्यकता छ

**Comment by madhusudhan1234** [comment]
I will start with Handling Events.

**Comment by Acesmndr** [comment]
I will take Conditional Rendering page as well.

**Comment by sabinbaniya** [comment]
Can anyone assign me with list and keys page?

**Comment by prajun7** [comment]
Hey guys,
It's great seeing all these active Nepali developers.
I will like to translate, the `Rendering Elements` page.
Thank you, @tesseralis @nootanghimire @samundrak @pachabhaiya for your hard work.

**Comment by prajun7** [comment]
Update: Working on `List and keys` as `Rendering Elements` was already taken.

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
